# Generated by Django 5.2.13 on 2026-05-03 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverprofile',
            name='otp_attempts',
            field=models.PositiveIntegerField(default=0, help_text='Number of failed OTP verification attempts'),
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='otp_generated_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when the last OTP was generated', null=True),
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='otp_secret',
            field=models.CharField(blank=True, help_text='Secret key for OTP generation', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='password_changed',
            field=models.BooleanField(default=False, help_text='Whether the driver has changed their temporary password'),
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='temp_password_expires_at',
            field=models.DateTimeField(blank=True, help_text='Expiry timestamp for temporary password (24 hours from onboarding)', null=True),
        ),
        migrations.AlterField(
            model_name='driverprofile',
            name='license_type',
            field=models.CharField(blank=True, choices=[('CLASS_A', 'Class A'), ('CLASS_B', 'Class B'), ('CLASS_C', 'Class C'), ('CLASS_D', 'Class D'), ('CLASS_E', 'Class E')], max_length=10, null=True),
        ),
        migrations.AddIndex(
            model_name='driverprofile',
            index=models.Index(fields=['otp_secret'], name='driver_prof_otp_sec_927284_idx'),
        ),
        migrations.AddIndex(
            model_name='driverprofile',
            index=models.Index(fields=['temp_password_expires_at'], name='driver_prof_temp_pa_df85ef_idx'),
        ),
    ]
