# Generated by Django 5.2.13 on 2026-05-04 16:42

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
import vehicles.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('oauth', '0002_driverprofile_otp_attempts_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('registration_number', models.CharField(db_index=True, help_text='Vehicle license plate/registration number', max_length=50, unique=True)),
                ('make', models.CharField(help_text='Vehicle manufacturer (e.g., Toyota, Isuzu)', max_length=100)),
                ('model', models.CharField(help_text='Vehicle model (e.g., Hilux, NPR)', max_length=100)),
                ('year', models.PositiveIntegerField(blank=True, help_text='Year of manufacture', null=True)),
                ('color', models.CharField(blank=True, max_length=50, null=True)),
                ('vehicle_type', models.CharField(choices=[('TRUCK', 'Truck'), ('VAN', 'Van'), ('PICKUP', 'Pickup'), ('BUS', 'Bus'), ('MINIBUS', 'Minibus'), ('CAR', 'Car'), ('MOTORCYCLE', 'Motorcycle'), ('TRAILER', 'Trailer'), ('OTHER', 'Other')], default='TRUCK', max_length=20)),
                ('vin', models.CharField(blank=True, db_index=True, help_text='Vehicle Identification Number (VIN/Chassis Number)', max_length=50, null=True, unique=True)),
                ('engine_number', models.CharField(blank=True, max_length=100, null=True)),
                ('load_capacity', models.DecimalField(blank=True, decimal_places=2, help_text='Load capacity in tons', max_digits=10, null=True)),
                ('seating_capacity', models.PositiveIntegerField(blank=True, help_text='Number of passengers (for buses/vans)', null=True)),
                ('fuel_type', models.CharField(choices=[('PETROL', 'Petrol'), ('DIESEL', 'Diesel'), ('ELECTRIC', 'Electric'), ('HYBRID', 'Hybrid'), ('CNG', 'CNG')], default='DIESEL', max_length=20)),
                ('fuel_tank_capacity', models.DecimalField(blank=True, decimal_places=2, help_text='Fuel tank capacity in liters', max_digits=8, null=True)),
                ('insurance_provider', models.CharField(blank=True, max_length=200, null=True)),
                ('insurance_policy_number', models.CharField(blank=True, max_length=100, null=True)),
                ('insurance_expiry_date', models.DateField(blank=True, help_text='Insurance policy expiry date', null=True)),
                ('registration_expiry_date', models.DateField(blank=True, help_text='Vehicle registration expiry date', null=True)),
                ('last_service_date', models.DateField(blank=True, null=True)),
                ('last_service_odometer', models.PositiveIntegerField(blank=True, help_text='Odometer reading at last service', null=True)),
                ('next_service_date', models.DateField(blank=True, null=True)),
                ('next_service_odometer', models.PositiveIntegerField(blank=True, help_text='Odometer reading for next service', null=True)),
                ('service_interval_km', models.PositiveIntegerField(blank=True, help_text='Service interval in kilometers', null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('UNDER_MAINTENANCE', 'Under Maintenance'), ('OUT_OF_SERVICE', 'Out of Service')], default='ACTIVE', max_length=20)),
                ('current_odometer', models.PositiveIntegerField(default=0, help_text='Current odometer reading')),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('current_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('image', models.ImageField(blank=True, help_text='Vehicle photo', null=True, upload_to=vehicles.models.vehicle_image_upload_path, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])])),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the vehicle', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether the vehicle is active in the system')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_driver', models.ForeignKey(blank=True, help_text='Currently assigned driver', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_vehicles', to='oauth.driverprofile')),
                ('company', models.ForeignKey(help_text='Company that owns this vehicle', on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='oauth.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_vehicles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vehicle',
                'verbose_name_plural': 'Vehicles',
                'db_table': 'vehicles',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FuelLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fill_date', models.DateField(default=django.utils.timezone.now)),
                ('odometer_reading', models.PositiveIntegerField(help_text='Odometer reading at time of fill')),
                ('liters', models.DecimalField(decimal_places=2, help_text='Liters of fuel added', max_digits=8)),
                ('price_per_liter', models.DecimalField(decimal_places=2, help_text='Price per liter', max_digits=8)),
                ('total_cost', models.DecimalField(decimal_places=2, help_text='Total cost of fuel', max_digits=10)),
                ('fuel_station', models.CharField(blank=True, help_text='Name of fuel station', max_length=200, null=True)),
                ('is_full_tank', models.BooleanField(default=True, help_text='Was the tank filled to full?')),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_fuel_logs', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fuel_logs', to='vehicles.vehicle')),
            ],
            options={
                'db_table': 'fuel_logs',
                'ordering': ['-fill_date'],
            },
        ),
        migrations.CreateModel(
            name='VehicleDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(choices=[('INSURANCE', 'Insurance Certificate'), ('REGISTRATION', 'Registration Certificate'), ('INSPECTION', 'Inspection Report'), ('SERVICE_RECORD', 'Service Record'), ('PURCHASE_INVOICE', 'Purchase Invoice'), ('OTHER', 'Other')], default='OTHER', max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('document_number', models.CharField(blank=True, max_length=100, null=True)),
                ('file', models.FileField(help_text='Upload document (PDF, JPG, PNG)', upload_to=vehicles.models.vehicle_document_upload_path, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'pdf'])])),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_vehicle_documents', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='vehicles.vehicle')),
            ],
            options={
                'db_table': 'vehicle_documents',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='VehicleExpense',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('expense_type', models.CharField(choices=[('FUEL', 'Fuel'), ('MAINTENANCE', 'Maintenance'), ('INSURANCE', 'Insurance'), ('REGISTRATION', 'Registration'), ('TOLL', 'Toll'), ('PARKING', 'Parking'), ('FINES', 'Fines/Penalties'), ('OTHER', 'Other')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.CharField(help_text='Brief description of the expense', max_length=500)),
                ('expense_date', models.DateField(default=django.utils.timezone.now)),
                ('odometer_reading', models.PositiveIntegerField(blank=True, help_text='Odometer reading at time of expense', null=True)),
                ('receipt', models.FileField(blank=True, help_text='Upload receipt', null=True, upload_to='vehicles/dc45cad3-981b-4bb4-b352-af84672023a7/expense_receipts/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'pdf'])])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_vehicle_expenses', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='vehicles.vehicle')),
            ],
            options={
                'db_table': 'vehicle_expenses',
                'ordering': ['-expense_date'],
            },
        ),
        migrations.CreateModel(
            name='VehicleServiceRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('service_type', models.CharField(choices=[('ROUTINE', 'Routine Service'), ('REPAIR', 'Repair'), ('INSPECTION', 'Inspection'), ('TIRE_CHANGE', 'Tire Change'), ('OIL_CHANGE', 'Oil Change'), ('BRAKE_SERVICE', 'Brake Service'), ('ENGINE_WORK', 'Engine Work'), ('BODY_WORK', 'Body Work'), ('OTHER', 'Other')], default='ROUTINE', max_length=30)),
                ('service_date', models.DateField()),
                ('odometer_reading', models.PositiveIntegerField(help_text='Odometer reading at time of service')),
                ('service_provider', models.CharField(help_text='Garage or service center name', max_length=200)),
                ('description', models.TextField(help_text='Description of service performed')),
                ('cost', models.DecimalField(decimal_places=2, help_text='Total cost of service', max_digits=10)),
                ('parts_replaced', models.TextField(blank=True, help_text='List of parts replaced', null=True)),
                ('next_service_date', models.DateField(blank=True, null=True)),
                ('next_service_odometer', models.PositiveIntegerField(blank=True, null=True)),
                ('receipt', models.FileField(blank=True, help_text='Upload service receipt/invoice', null=True, upload_to='vehicles/519a4cd8-2d5e-44fc-a77d-3c9dca9a33b0/service_receipts/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'pdf'])])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_service_records', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_records', to='vehicles.vehicle')),
            ],
            options={
                'db_table': 'vehicle_service_records',
                'ordering': ['-service_date'],
            },
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['company', 'status'], name='vehicles_company_bd8720_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['registration_number'], name='vehicles_registr_eb8990_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['assigned_driver'], name='vehicles_assigne_8ad378_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['vehicle_type'], name='vehicles_vehicle_d54349_idx'),
        ),
        migrations.AddIndex(
            model_name='fuellog',
            index=models.Index(fields=['vehicle', 'fill_date'], name='fuel_logs_vehicle_04c9ed_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicledocument',
            index=models.Index(fields=['vehicle', 'document_type'], name='vehicle_doc_vehicle_746dfa_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicledocument',
            index=models.Index(fields=['expiry_date'], name='vehicle_doc_expiry__d07ca2_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicleexpense',
            index=models.Index(fields=['vehicle', 'expense_type'], name='vehicle_exp_vehicle_ef1608_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicleexpense',
            index=models.Index(fields=['expense_date'], name='vehicle_exp_expense_d3bc0d_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicleservicerecord',
            index=models.Index(fields=['vehicle', 'service_date'], name='vehicle_ser_vehicle_65eb09_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicleservicerecord',
            index=models.Index(fields=['service_type'], name='vehicle_ser_service_dd7f89_idx'),
        ),
    ]
