# Generated by Django 5.2.13 on 2026-05-08 09:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicleexpense',
            name='receipt',
            field=models.FileField(blank=True, help_text='Upload receipt', null=True, upload_to='vehicles/2f500ce6-a895-467c-9e4b-d73fdff2eb13/expense_receipts/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'pdf'])]),
        ),
        migrations.AlterField(
            model_name='vehicleservicerecord',
            name='receipt',
            field=models.FileField(blank=True, help_text='Upload service receipt/invoice', null=True, upload_to='vehicles/430d33e9-0f05-4244-9d8e-60eff22d801c/service_receipts/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'pdf'])]),
        ),
    ]
