# Generated by Cursor on 2026-06-10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0002_alter_vehicleexpense_receipt_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['company', '-created_at'], name='vehicles_company_1d4a0c_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['company', 'vehicle_type'], name='vehicles_company_2d61e9_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['company', 'assigned_driver'], name='vehicles_company_3ed7b4_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['company', 'is_active'], name='vehicles_company_ef4c91_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['status'], name='vehicles_status_9e35f2_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['created_at'], name='vehicles_created_f0b6d2_idx'),
        ),
    ]
