# Generated by Django 5.2.13 on 2026-05-08 09:05

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import trips.models
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('oauth', '0002_driverprofile_otp_attempts_and_more'),
        ('vehicles', '0002_alter_vehicleexpense_receipt_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('trip_number', models.CharField(db_index=True, help_text='Unique trip reference number', max_length=50, unique=True)),
                ('pickup_location', models.CharField(help_text='Starting point / pickup location', max_length=500)),
                ('destination', models.CharField(help_text='Final destination', max_length=500)),
                ('waypoints', models.JSONField(blank=True, help_text='List of stops/waypoints along the route', null=True)),
                ('planned_departure_time', models.DateTimeField(help_text='Scheduled departure time')),
                ('planned_arrival_time', models.DateTimeField(blank=True, help_text='Estimated arrival time', null=True)),
                ('actual_departure_time', models.DateTimeField(blank=True, help_text='Actual departure time', null=True)),
                ('actual_arrival_time', models.DateTimeField(blank=True, help_text='Actual arrival time', null=True)),
                ('start_odometer', models.PositiveIntegerField(blank=True, help_text='Odometer reading at start of trip', null=True)),
                ('end_odometer', models.PositiveIntegerField(blank=True, help_text='Odometer reading at end of trip', null=True)),
                ('start_odometer_photo', models.ImageField(blank=True, help_text='Photo of odometer at trip start', null=True, upload_to=trips.models.trip_image_upload_path, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'])])),
                ('end_odometer_photo', models.ImageField(blank=True, help_text='Photo of odometer at trip end', null=True, upload_to=trips.models.trip_image_upload_path, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'])])),
                ('cargo_description', models.TextField(blank=True, help_text='Description of cargo being transported', null=True)),
                ('cargo_weight', models.DecimalField(blank=True, decimal_places=2, help_text='Cargo weight in tons', max_digits=10, null=True)),
                ('number_of_stops', models.PositiveIntegerField(default=1, help_text='Number of delivery stops')),
                ('deliveries_completed', models.PositiveIntegerField(default=0, help_text='Number of successful deliveries')),
                ('revenue_model', models.CharField(choices=[('FIXED_RATE', 'Fixed Rate'), ('PER_KM', 'Per Kilometer'), ('PER_DELIVERY', 'Per Delivery'), ('CONTRACT', 'Contract Based'), ('HOURLY', 'Hourly Rate')], default='FIXED_RATE', max_length=20)),
                ('revenue_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total revenue for this trip', max_digits=12)),
                ('rate_per_km', models.DecimalField(blank=True, decimal_places=2, help_text='Rate per kilometer (if PER_KM model)', max_digits=10, null=True)),
                ('fuel_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Fuel cost for this trip', max_digits=10)),
                ('toll_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Toll charges', max_digits=10)),
                ('other_expenses', models.DecimalField(decimal_places=2, help_text='Other miscellaneous expenses', max_digits=10)),
                ('status', models.CharField(choices=[('PLANNED', 'Planned'), ('ONGOING', 'Ongoing'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('FLAGGED', 'Flagged'), ('DELAYED', 'Delayed')], default='PLANNED', max_length=20)),
                ('is_flagged', models.BooleanField(default=False, help_text='Flagged for review (unusual data, fraud detection)')),
                ('flag_reason', models.TextField(blank=True, help_text='Reason for flagging the trip', null=True)),
                ('is_approved', models.BooleanField(default=False, help_text='Approved by fleet manager (for flagged trips)')),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('customer_name', models.CharField(blank=True, help_text='Customer/client name', max_length=200, null=True)),
                ('customer_contact', models.CharField(blank=True, help_text='Customer contact number', max_length=100, null=True)),
                ('customer_reference', models.CharField(blank=True, help_text='Customer PO/reference number', max_length=100, null=True)),
                ('driver_notes', models.TextField(blank=True, help_text='Notes from the driver about the trip', null=True)),
                ('manager_notes', models.TextField(blank=True, help_text='Notes from the fleet manager', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_trips', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(help_text='Company that owns this trip', on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='oauth.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_trips', to=settings.AUTH_USER_MODEL)),
                ('driver', models.ForeignKey(blank=True, help_text='Driver assigned to this trip', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trips', to='oauth.driverprofile')),
                ('vehicle', models.ForeignKey(help_text='Vehicle assigned to this trip', on_delete=django.db.models.deletion.PROTECT, related_name='trips', to='vehicles.vehicle')),
            ],
            options={
                'verbose_name': 'Trip',
                'verbose_name_plural': 'Trips',
                'db_table': 'trips',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TripExpense',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('expense_type', models.CharField(choices=[('FUEL', 'Fuel'), ('TOLL', 'Toll'), ('PARKING', 'Parking'), ('LOADING', 'Loading/Unloading'), ('MEALS', 'Meals & Refreshments'), ('ACCOMMODATION', 'Accommodation'), ('REPAIRS', 'Emergency Repairs'), ('OTHER', 'Other')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.CharField(help_text='Description of the expense', max_length=500)),
                ('expense_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('location', models.CharField(blank=True, help_text='Where the expense occurred', max_length=300, null=True)),
                ('receipt', models.ImageField(blank=True, help_text='Receipt photo/scan', null=True, upload_to='trips/878d77a9-17d8-4013-aba1-9320d644bbe1/expense_receipts/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'pdf'])])),
                ('is_verified', models.BooleanField(default=False, help_text='Verified by fleet manager')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_trip_expenses', to=settings.AUTH_USER_MODEL)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detailed_expenses', to='trips.trip')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_trip_expenses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'trip_expenses',
                'ordering': ['-expense_date'],
            },
        ),
        migrations.CreateModel(
            name='TripStop',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stop_number', models.PositiveIntegerField(help_text='Order of this stop in the trip')),
                ('location', models.CharField(help_text='Stop location/address', max_length=500)),
                ('contact_person', models.CharField(blank=True, max_length=200, null=True)),
                ('contact_phone', models.CharField(blank=True, max_length=50, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('arrival_time', models.DateTimeField(blank=True, null=True)),
                ('departure_time', models.DateTimeField(blank=True, null=True)),
                ('odometer_reading', models.PositiveIntegerField(blank=True, null=True)),
                ('items_delivered', models.TextField(blank=True, help_text='Description of items delivered at this stop', null=True)),
                ('delivery_proof_photo', models.ImageField(blank=True, help_text='Photo proof of delivery', null=True, upload_to='trips/450e885c-449c-4275-9333-a746b2bea3f1/delivery_proofs/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'])])),
                ('recipient_signature', models.CharField(blank=True, help_text='Name of person who received delivery', max_length=200, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='trips.trip')),
            ],
            options={
                'db_table': 'trip_stops',
                'ordering': ['trip', 'stop_number'],
            },
        ),
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['company', 'status'], name='trips_company_1b3206_idx'),
        ),
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['vehicle', 'status'], name='trips_vehicle_06cd2b_idx'),
        ),
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['driver', 'status'], name='trips_driver__f38efc_idx'),
        ),
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['trip_number'], name='trips_trip_nu_2e1533_idx'),
        ),
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['planned_departure_time'], name='trips_planned_8c5bbd_idx'),
        ),
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['status', 'is_flagged'], name='trips_status_15318f_idx'),
        ),
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['created_at'], name='trips_created_4fa010_idx'),
        ),
        migrations.AddIndex(
            model_name='tripexpense',
            index=models.Index(fields=['trip', 'expense_type'], name='trip_expens_trip_id_6b282c_idx'),
        ),
        migrations.AddIndex(
            model_name='tripexpense',
            index=models.Index(fields=['is_verified'], name='trip_expens_is_veri_cbfc6d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='tripstop',
            unique_together={('trip', 'stop_number')},
        ),
    ]
