# Generated by Django 6.0.5 on 2026-05-17 12:49

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='other_expenses',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Other miscellaneous expenses', max_digits=10),
        ),
        migrations.AlterField(
            model_name='tripexpense',
            name='receipt',
            field=models.ImageField(blank=True, help_text='Receipt photo/scan', null=True, upload_to='trips/bdbc4faa-28bd-45bc-8cd9-eb741f1f54b2/expense_receipts/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'pdf'])]),
        ),
        migrations.AlterField(
            model_name='tripstop',
            name='delivery_proof_photo',
            field=models.ImageField(blank=True, help_text='Photo proof of delivery', null=True, upload_to='trips/69b5bbce-a6ac-4461-a5c3-7411cbdf98b9/delivery_proofs/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'])]),
        ),
    ]
